### ISSUE TITLE
Last Modified date is not getting updated

### ISSUE THREAD

**Issue by mzafer** [Travelbee-VN/dio-304-cache#6]
Looks like only the very first last modified date received in the response is being used every time the request is sent to the  server. Any updated value to the last modified date returned by the server in subsequent response is not updated to the cache.

**Comment by mzafer** [comment]
#7  Created a pull request, please review if the fix will resolve the issue. It does work for me.

**Comment by luunc** [comment]
@mzafer , thank for your contribution.
